name: cron
on: [push]
#      schedule:
#        - cron: "0 1 * * *" #Runs everyday at 1:00AM

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: execute py script # run the run.py to get the latest data
          run: |
            python main.py
        env:
          url: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }} # if run.py requires passwords..etc, set it as secrets
          password: ${{ secrets.PASSWORD }} # if run.py requires passwords..etc, set it as secrets